/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/taxonomy-versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List taxonomy versions of an exam family */
        get: operations["listTaxonomyVersions"];
        put?: never;
        /** Create a taxonomy draft */
        post: operations["createTaxonomyDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/taxonomy-versions/{taxonomyVersionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taxonomyVersionId: components["parameters"]["TaxonomyVersionId"];
            };
            cookie?: never;
        };
        /** Read one taxonomy version */
        get: operations["getTaxonomyVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/taxonomy-versions/{taxonomyVersionId}/concept-nodes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taxonomyVersionId: components["parameters"]["TaxonomyVersionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a concept node to a draft */
        post: operations["addConceptNode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/taxonomy-versions/{taxonomyVersionId}/concept-nodes/{conceptNodeId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taxonomyVersionId: components["parameters"]["TaxonomyVersionId"];
                conceptNodeId: components["parameters"]["ConceptNodeId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a concept node from a draft */
        delete: operations["removeConceptNode"];
        options?: never;
        head?: never;
        /** Move a concept node under a new parent */
        patch: operations["moveConceptNode"];
        trace?: never;
    };
    "/v1/taxonomy-versions/{taxonomyVersionId}/prerequisite-edges": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taxonomyVersionId: components["parameters"]["TaxonomyVersionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a prerequisite edge to a draft */
        post: operations["addPrerequisiteEdge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/taxonomy-versions/{taxonomyVersionId}/publication": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taxonomyVersionId: components["parameters"]["TaxonomyVersionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish a taxonomy version */
        post: operations["publishTaxonomyVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/taxonomy-versions/{taxonomyVersionId}/concept-subtree": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taxonomyVersionId: components["parameters"]["TaxonomyVersionId"];
            };
            cookie?: never;
        };
        /** Read a concept subtree, optionally depth-limited */
        get: operations["getConceptSubtree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/taxonomy-versions/{taxonomyVersionId}/concepts/{conceptIdentityId}/prerequisites": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taxonomyVersionId: components["parameters"]["TaxonomyVersionId"];
                conceptIdentityId: string;
            };
            cookie?: never;
        };
        /** Read what a concept requires and what requires it */
        get: operations["getConceptPrerequisites"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List exams */
        get: operations["listExams"];
        put?: never;
        /** Create an exam */
        post: operations["createExam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exam-profile-versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an exam profile draft */
        post: operations["createProfileDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exam-profile-versions/{profileVersionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profileVersionId: components["parameters"]["ProfileVersionId"];
            };
            cookie?: never;
        };
        /** Read one exam profile version */
        get: operations["getExamProfileVersion"];
        /** Replace the content of a profile draft */
        put: operations["updateProfileDraft"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exam-profile-versions/{profileVersionId}/publication": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profileVersionId: components["parameters"]["ProfileVersionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish an exam profile version */
        post: operations["publishProfileVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exam-profile-versions/{profileVersionId}/supersession": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profileVersionId: components["parameters"]["ProfileVersionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Supersede a published profile version */
        post: operations["supersedeProfileVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/taxonomy-migrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a taxonomy migration */
        post: operations["createMigration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/taxonomy-migrations/{migrationId}/mappings": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                migrationId: components["parameters"]["MigrationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a mapping to a migration */
        post: operations["addMapping"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/taxonomy-migrations/{migrationId}/dry-run": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                migrationId: components["parameters"]["MigrationId"];
            };
            cookie?: never;
        };
        /** Read the stored dry-run preview */
        get: operations["getMigrationDryRun"];
        put?: never;
        /** Run a migration dry run */
        post: operations["runDryRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/taxonomy-migrations/{migrationId}/execution": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                migrationId: components["parameters"]["MigrationId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute a dispositioned migration */
        post: operations["executeMigration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 9457 Problem Details with a stable machine-readable code. */
        ProblemDetails: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            code: components["schemas"]["ErrorCode"];
            retryable: boolean;
            correlationId: string;
            errors?: {
                field: string;
                message: string;
            }[];
        };
        /**
         * @description The closed error taxonomy (ENGINEERING-HANDBOOK §8).
         * @enum {string}
         */
        ErrorCode: "Validation" | "Authentication" | "Authorization" | "Entitlement" | "NotFound" | "Conflict" | "PreconditionFailed" | "RuleViolation" | "RateLimited" | "Unavailable";
        PageInfo: {
            hasNextPage: boolean;
            nextCursor?: string | null;
        };
        TaxonomyWriteResult: {
            /** Format: uuid */
            taxonomyVersionId: string;
            aggregateVersion: number;
        };
        ProfileWriteResult: {
            /** Format: uuid */
            profileVersionId: string;
            aggregateVersion: number;
        };
        MigrationWriteResult: {
            /** Format: uuid */
            migrationId: string;
            aggregateVersion: number;
        };
        ExecutionResult: {
            /** Format: uuid */
            migrationId: string;
            aggregateVersion: number;
            migratedConceptCount: number;
            chunkCount: number;
        };
        TaxonomyVersionSummary: {
            /** Format: uuid */
            taxonomyVersionId: string;
            examFamily: string;
            academicYear: string;
            state: components["schemas"]["LifecycleState"];
            /** Format: date-time */
            publishedAt: string | null;
            nodeCount: number;
            prerequisiteCount: number;
            aggregateVersion: number;
        };
        TaxonomyVersionDetail: components["schemas"]["TaxonomyVersionSummary"] & {
            nodes: components["schemas"]["ConceptNode"][];
        };
        TaxonomyVersionPage: {
            items: components["schemas"]["TaxonomyVersionSummary"][];
            pageInfo: components["schemas"]["PageInfo"];
        };
        /** @enum {string} */
        LifecycleState: "draft" | "published" | "superseded";
        ConceptNode: {
            /** Format: uuid */
            conceptNodeId: string;
            /** Format: uuid */
            conceptIdentityId: string;
            /** Format: uuid */
            parentNodeId: string | null;
            displayName: string;
            examWeight: number;
            depth: number;
            estimatedTeachingHours: number;
        };
        ConceptSubtree: {
            /** Format: uuid */
            rootNodeId: string;
            depthLimit: number | null;
            nodes: components["schemas"]["ConceptNode"][];
        };
        ConceptPrerequisites: {
            /** Format: uuid */
            conceptIdentityId: string;
            requires: components["schemas"]["PrerequisiteRelation"][];
            requiredBy: components["schemas"]["PrerequisiteRelation"][];
        };
        PrerequisiteRelation: {
            /** Format: uuid */
            conceptIdentityId: string;
            strength: number;
        };
        Exam: {
            /** Format: uuid */
            examId: string;
            code: string;
            displayName: string;
            jurisdiction: string;
            conductingBody: string;
            activeProfileVersions: {
                academicYear: string;
                /** Format: uuid */
                profileVersionId: string;
            }[];
        };
        ExamPage: {
            items: components["schemas"]["Exam"][];
            pageInfo: components["schemas"]["PageInfo"];
        };
        SectionSpec: {
            ordinal: number;
            name: string;
            subject: string;
            itemCount: number;
            itemTypeMix: {
                [key: string]: number;
            };
            maxMarks: number;
            sectionTimingMinutes: number | null;
        };
        ItemTypeAllowance: {
            itemType: string;
            sectionOrdinals: number[];
        };
        TimingPolicy: {
            totalDurationMinutes: number;
            sectionLocking: boolean;
            warningThresholdsMinutes: number[];
            autoSubmitOnExpiry: boolean;
        };
        NavigationPolicy: {
            crossSectionNavigation: boolean;
            allowMarkForReview: boolean;
            allowAnswerChange: boolean;
            allowClearResponse: boolean;
        };
        Condition: {
            /** @enum {string} */
            kind: "UNATTEMPTED" | "EXACT_MATCH" | "NO_MATCH" | "ALL_CORRECT_SELECTED" | "PARTIAL_CORRECT_SELECTED" | "ANY_INCORRECT_SELECTED" | "MATCHING_PAIRS_CORRECT" | "ALWAYS";
            minCorrect?: number;
            noIncorrect?: boolean;
            count?: number;
        };
        Award: {
            /** @enum {string} */
            kind: "FIXED" | "PER_CORRECT" | "FULL_MARKS";
            marks?: number;
        };
        MarkingRule: {
            id: string;
            appliesTo: {
                itemTypes: string[];
                sectionOrdinals?: number[];
            };
            condition: components["schemas"]["Condition"];
            award: components["schemas"]["Award"];
        };
        MarkingRuleSet: {
            schemaVersion: number;
            rules: components["schemas"]["MarkingRule"][];
        };
        NumericAnswerSpec: {
            expectedValue: string;
            /** @enum {string} */
            comparisonMode: "EXACT" | "ABSOLUTE_TOLERANCE" | "RELATIVE_TOLERANCE" | "SIGNIFICANT_FIGURES" | "RANGE";
            toleranceValue?: string;
            significantFigures?: number;
            rangeMin?: string;
            rangeMax?: string;
            unit?: {
                canonical: string;
                acceptedEquivalents: string[];
                required: boolean;
            };
            acceptedForms: ("DECIMAL" | "FRACTION" | "SCIENTIFIC")[];
            normalization?: {
                trimWhitespace: boolean;
                stripThousandsSeparator: boolean;
                unicodeMinusToAscii: boolean;
                caseInsensitiveUnit: boolean;
            };
        };
        ExamProfileVersionDetail: {
            /** Format: uuid */
            profileVersionId: string;
            /** Format: uuid */
            examId: string;
            academicYear: string;
            state: components["schemas"]["LifecycleState"];
            /** Format: uuid */
            taxonomyVersionId: string;
            totalMarks: number;
            markingRuleSetHash: string | null;
            markingRuleSet: components["schemas"]["MarkingRuleSet"];
            sections: components["schemas"]["SectionSpec"][];
            itemTypeAllowances: components["schemas"]["ItemTypeAllowance"][];
            aggregateVersion: number;
        };
        MigrationException: {
            /** @enum {string} */
            kind: "AMBIGUOUS_MAPPING" | "UNMAPPED";
            mappingKind?: components["schemas"]["MappingKind"];
            concepts: string[];
            /** @enum {string} */
            disposition: "pending" | "accepted" | "rejected";
            reason: string;
        };
        /** @enum {string} */
        MappingKind: "IDENTITY" | "RENAME" | "MOVE" | "SPLIT" | "MERGE" | "REMOVAL";
        MigrationDryRun: {
            schemaVersion: number;
            /** Format: uuid */
            migrationId: string;
            /** Format: uuid */
            fromVersionId: string;
            /** Format: uuid */
            toVersionId: string;
            autoMigratableCount: number;
            exceptions: components["schemas"]["MigrationException"][];
            invalidMappings: {
                mappingIndex: number;
                mappingKind: components["schemas"]["MappingKind"];
                concepts: string[];
                reason: string;
            }[];
        };
        CreateTaxonomyDraftRequest: {
            examFamily: string;
            academicYear: string;
        };
        AddConceptNodeRequest: {
            /** Format: uuid */
            conceptIdentityId: string;
            /** Format: uuid */
            parentNodeId?: string;
            displayName: string;
            examWeight: number;
            estimatedTeachingHours: number;
        };
        MoveConceptNodeRequest: {
            /** Format: uuid */
            newParentNodeId: string;
        };
        AddPrerequisiteEdgeRequest: {
            /** Format: uuid */
            fromConceptIdentityId: string;
            /** Format: uuid */
            toConceptIdentityId: string;
            strength: number;
        };
        CreateExamRequest: {
            code: string;
            displayName: string;
            jurisdiction: string;
            conductingBody: string;
        };
        ProfileDraftContent: {
            sections: components["schemas"]["SectionSpec"][];
            totalMarks: number;
            timingPolicy: components["schemas"]["TimingPolicy"];
            navigationPolicy: components["schemas"]["NavigationPolicy"];
            markingRuleSet: components["schemas"]["MarkingRuleSet"];
            toleranceDefault?: components["schemas"]["NumericAnswerSpec"];
            itemTypeAllowances: components["schemas"]["ItemTypeAllowance"][];
        };
        CreateProfileDraftRequest: components["schemas"]["ProfileDraftContent"] & {
            /** Format: uuid */
            examId: string;
            academicYear: string;
            /** Format: uuid */
            taxonomyVersionId: string;
        };
        CreateMigrationRequest: {
            /** Format: uuid */
            fromVersionId: string;
            /** Format: uuid */
            toVersionId: string;
        };
        AddMappingRequest: {
            kind: components["schemas"]["MappingKind"];
            from: string[];
            to: string[];
            /** @enum {string} */
            disposition?: "pending" | "accepted" | "rejected";
        };
    };
    responses: {
        /** @description The request was malformed. */
        ValidationProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description The principal may not perform this operation. */
        AuthorizationProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description No such resource. */
        NotFoundProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description The resource changed under the caller, or a uniqueness rule was broken. */
        ConflictProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description A domain rule refused the change. */
        RuleViolationProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        CorrelationId: string;
        /** @description The aggregate version the caller believes it is changing. */
        IfMatch: string;
        /** @description Required on publication and execution, which must not repeat. */
        IdempotencyKey: string;
        /** @description Opaque forward cursor. There is no offset parameter by design. */
        Cursor: string;
        Limit: number;
        TaxonomyVersionId: string;
        ConceptNodeId: string;
        ProfileVersionId: string;
        MigrationId: string;
        /** @description Allowlisted sort fields. Anything else is rejected. */
        TaxonomyVersionSort: "academicYear" | "-academicYear" | "publishedAt" | "-publishedAt";
        /** @description Allowlisted filter field. */
        TaxonomyVersionFilterState: "draft" | "published" | "superseded";
        ExamSort: "code" | "-code" | "displayName" | "-displayName";
        ExamFilterJurisdiction: string;
    };
    requestBodies: never;
    headers: {
        /** @description The aggregate version, quoted. Send it back as If-Match. */
        ETag: string;
        /** @description The correlation id, echoed on every response including errors. */
        CorrelationId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listTaxonomyVersions: {
        parameters: {
            query: {
                /** @description Opaque forward cursor. There is no offset parameter by design. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
                /** @description Allowlisted sort fields. Anything else is rejected. */
                sort?: components["parameters"]["TaxonomyVersionSort"];
                /** @description Allowlisted filter field. */
                state?: components["parameters"]["TaxonomyVersionFilterState"];
                examFamily: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of taxonomy versions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonomyVersionPage"];
                };
            };
            403: components["responses"]["AuthorizationProblem"];
        };
    };
    createTaxonomyDraft: {
        parameters: {
            query?: never;
            header?: {
                "X-Correlation-Id"?: components["parameters"]["CorrelationId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaxonomyDraftRequest"];
            };
        };
        responses: {
            /** @description The draft was created. */
            201: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    "X-Correlation-Id": components["headers"]["CorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonomyWriteResult"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            403: components["responses"]["AuthorizationProblem"];
        };
    };
    getTaxonomyVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taxonomyVersionId: components["parameters"]["TaxonomyVersionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The taxonomy version. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonomyVersionDetail"];
                };
            };
            403: components["responses"]["AuthorizationProblem"];
            404: components["responses"]["NotFoundProblem"];
        };
    };
    addConceptNode: {
        parameters: {
            query?: never;
            header: {
                /** @description The aggregate version the caller believes it is changing. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                taxonomyVersionId: components["parameters"]["TaxonomyVersionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddConceptNodeRequest"];
            };
        };
        responses: {
            /** @description The node was added. */
            201: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonomyWriteResult"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            403: components["responses"]["AuthorizationProblem"];
            404: components["responses"]["NotFoundProblem"];
            409: components["responses"]["ConflictProblem"];
            422: components["responses"]["RuleViolationProblem"];
        };
    };
    removeConceptNode: {
        parameters: {
            query?: never;
            header: {
                /** @description The aggregate version the caller believes it is changing. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                taxonomyVersionId: components["parameters"]["TaxonomyVersionId"];
                conceptNodeId: components["parameters"]["ConceptNodeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The node was removed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonomyWriteResult"];
                };
            };
            403: components["responses"]["AuthorizationProblem"];
            404: components["responses"]["NotFoundProblem"];
            409: components["responses"]["ConflictProblem"];
            422: components["responses"]["RuleViolationProblem"];
        };
    };
    moveConceptNode: {
        parameters: {
            query?: never;
            header: {
                /** @description The aggregate version the caller believes it is changing. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                taxonomyVersionId: components["parameters"]["TaxonomyVersionId"];
                conceptNodeId: components["parameters"]["ConceptNodeId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveConceptNodeRequest"];
            };
        };
        responses: {
            /** @description The node was moved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonomyWriteResult"];
                };
            };
            403: components["responses"]["AuthorizationProblem"];
            404: components["responses"]["NotFoundProblem"];
            409: components["responses"]["ConflictProblem"];
            422: components["responses"]["RuleViolationProblem"];
        };
    };
    addPrerequisiteEdge: {
        parameters: {
            query?: never;
            header: {
                /** @description The aggregate version the caller believes it is changing. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                taxonomyVersionId: components["parameters"]["TaxonomyVersionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddPrerequisiteEdgeRequest"];
            };
        };
        responses: {
            /** @description The edge was added. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonomyWriteResult"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            403: components["responses"]["AuthorizationProblem"];
            404: components["responses"]["NotFoundProblem"];
            409: components["responses"]["ConflictProblem"];
            422: components["responses"]["RuleViolationProblem"];
        };
    };
    publishTaxonomyVersion: {
        parameters: {
            query?: never;
            header: {
                /** @description The aggregate version the caller believes it is changing. */
                "If-Match": components["parameters"]["IfMatch"];
                /** @description Required on publication and execution, which must not repeat. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                taxonomyVersionId: components["parameters"]["TaxonomyVersionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The version was published. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonomyWriteResult"];
                };
            };
            403: components["responses"]["AuthorizationProblem"];
            404: components["responses"]["NotFoundProblem"];
            409: components["responses"]["ConflictProblem"];
            422: components["responses"]["RuleViolationProblem"];
        };
    };
    getConceptSubtree: {
        parameters: {
            query: {
                rootNodeId: string;
                depthLimit?: number;
            };
            header?: never;
            path: {
                taxonomyVersionId: components["parameters"]["TaxonomyVersionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The subtree. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConceptSubtree"];
                };
            };
            403: components["responses"]["AuthorizationProblem"];
            404: components["responses"]["NotFoundProblem"];
        };
    };
    getConceptPrerequisites: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                taxonomyVersionId: components["parameters"]["TaxonomyVersionId"];
                conceptIdentityId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The prerequisite relations. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConceptPrerequisites"];
                };
            };
            403: components["responses"]["AuthorizationProblem"];
            404: components["responses"]["NotFoundProblem"];
        };
    };
    listExams: {
        parameters: {
            query?: {
                /** @description Opaque forward cursor. There is no offset parameter by design. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
                sort?: components["parameters"]["ExamSort"];
                jurisdiction?: components["parameters"]["ExamFilterJurisdiction"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of exams. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamPage"];
                };
            };
            403: components["responses"]["AuthorizationProblem"];
        };
    };
    createExam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExamRequest"];
            };
        };
        responses: {
            /** @description The exam was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        examId: string;
                    };
                };
            };
            400: components["responses"]["ValidationProblem"];
            403: components["responses"]["AuthorizationProblem"];
            409: components["responses"]["ConflictProblem"];
        };
    };
    createProfileDraft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProfileDraftRequest"];
            };
        };
        responses: {
            /** @description The draft was created. */
            201: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileWriteResult"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            403: components["responses"]["AuthorizationProblem"];
            404: components["responses"]["NotFoundProblem"];
            422: components["responses"]["RuleViolationProblem"];
        };
    };
    getExamProfileVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profileVersionId: components["parameters"]["ProfileVersionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The profile version. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamProfileVersionDetail"];
                };
            };
            403: components["responses"]["AuthorizationProblem"];
            404: components["responses"]["NotFoundProblem"];
        };
    };
    updateProfileDraft: {
        parameters: {
            query?: never;
            header: {
                /** @description The aggregate version the caller believes it is changing. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                profileVersionId: components["parameters"]["ProfileVersionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileDraftContent"];
            };
        };
        responses: {
            /** @description The draft was updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileWriteResult"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            403: components["responses"]["AuthorizationProblem"];
            404: components["responses"]["NotFoundProblem"];
            409: components["responses"]["ConflictProblem"];
            422: components["responses"]["RuleViolationProblem"];
        };
    };
    publishProfileVersion: {
        parameters: {
            query?: never;
            header: {
                /** @description The aggregate version the caller believes it is changing. */
                "If-Match": components["parameters"]["IfMatch"];
                /** @description Required on publication and execution, which must not repeat. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                profileVersionId: components["parameters"]["ProfileVersionId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @default false */
                    activate?: boolean;
                };
            };
        };
        responses: {
            /** @description The profile version was published. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileWriteResult"];
                };
            };
            403: components["responses"]["AuthorizationProblem"];
            404: components["responses"]["NotFoundProblem"];
            409: components["responses"]["ConflictProblem"];
            422: components["responses"]["RuleViolationProblem"];
        };
    };
    supersedeProfileVersion: {
        parameters: {
            query?: never;
            header: {
                /** @description The aggregate version the caller believes it is changing. */
                "If-Match": components["parameters"]["IfMatch"];
                /** @description Required on publication and execution, which must not repeat. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                profileVersionId: components["parameters"]["ProfileVersionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The profile version was superseded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileWriteResult"];
                };
            };
            403: components["responses"]["AuthorizationProblem"];
            404: components["responses"]["NotFoundProblem"];
            409: components["responses"]["ConflictProblem"];
            422: components["responses"]["RuleViolationProblem"];
        };
    };
    createMigration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMigrationRequest"];
            };
        };
        responses: {
            /** @description The migration was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationWriteResult"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            403: components["responses"]["AuthorizationProblem"];
            404: components["responses"]["NotFoundProblem"];
        };
    };
    addMapping: {
        parameters: {
            query?: never;
            header: {
                /** @description The aggregate version the caller believes it is changing. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                migrationId: components["parameters"]["MigrationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMappingRequest"];
            };
        };
        responses: {
            /** @description The mapping was added. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationWriteResult"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            403: components["responses"]["AuthorizationProblem"];
            404: components["responses"]["NotFoundProblem"];
            409: components["responses"]["ConflictProblem"];
            422: components["responses"]["RuleViolationProblem"];
        };
    };
    getMigrationDryRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                migrationId: components["parameters"]["MigrationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The stored dry run, or null if none has been run. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationDryRun"] | null;
                };
            };
            403: components["responses"]["AuthorizationProblem"];
            404: components["responses"]["NotFoundProblem"];
        };
    };
    runDryRun: {
        parameters: {
            query?: never;
            header: {
                /** @description The aggregate version the caller believes it is changing. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                migrationId: components["parameters"]["MigrationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The dry-run preview. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MigrationDryRun"];
                };
            };
            403: components["responses"]["AuthorizationProblem"];
            404: components["responses"]["NotFoundProblem"];
            409: components["responses"]["ConflictProblem"];
        };
    };
    executeMigration: {
        parameters: {
            query?: never;
            header: {
                /** @description The aggregate version the caller believes it is changing. */
                "If-Match": components["parameters"]["IfMatch"];
                /** @description Required on publication and execution, which must not repeat. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                migrationId: components["parameters"]["MigrationId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    chunkSize?: number;
                };
            };
        };
        responses: {
            /** @description Execution finished. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionResult"];
                };
            };
            403: components["responses"]["AuthorizationProblem"];
            404: components["responses"]["NotFoundProblem"];
            409: components["responses"]["ConflictProblem"];
            422: components["responses"]["RuleViolationProblem"];
        };
    };
}
